### ISSUE TITLE
Error after install plugin in my cheshire instance

### ISSUE THREAD

**Issue by PhantomNX20** [lucagobbi/catcloak#1]
**Describe the bug**
cheshire_cat_core  | ERROR:    Exception in ASGI application
cheshire_cat_core  | Traceback (most recent call last):
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
cheshire_cat_core  |     result = await app(  # type: ignore[func-returns-value]
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
cheshire_cat_core  |     return await self.app(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
cheshire_cat_core  |     await super().__call__(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
cheshire_cat_core  |     await self.middleware_stack(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
cheshire_cat_core  |     raise exc
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
cheshire_cat_core  |     await self.app(scope, receive, _send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
cheshire_cat_core  |     await self.app(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
cheshire_cat_core  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
cheshire_cat_core  |     raise exc
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
cheshire_cat_core  |     await app(scope, receive, sender)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
cheshire_cat_core  |     await self.middleware_stack(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
cheshire_cat_core  |     await route.handle(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
cheshire_cat_core  |     await self.app(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
cheshire_cat_core  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
cheshire_cat_core  |     raise exc
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
cheshire_cat_core  |     await app(scope, receive, sender)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
cheshire_cat_core  |     response = await func(request)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 269, in app
cheshire_cat_core  |     solved_result = await solve_dependencies(
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 600, in solve_dependencies
cheshire_cat_core  |     solved = await call(**sub_values)
cheshire_cat_core  |   File "/app/cat/auth/connection.py", line 50, in __call__
cheshire_cat_core  |     user: AuthUserInfo = await ah.authorize_user_from_credential(
cheshire_cat_core  |   File "/app/cat/factory/custom_auth_handler.py", line 38, in authorize_user_from_credential
cheshire_cat_core  |     return await self.authorize_user_from_key(
cheshire_cat_core  | TypeError: KeycloakAuthHandler.authorize_user_from_key() missing 1 required positional argument: 'auth_permission'

this is the log of my cheshire, i don't know why it doesn't work, i follow the guide step by step

**To Reproduce**
Install the plugin from cheshire plugin page, and you will see the error

**Comment by lucagobbi** [comment]
You're right! I've updated the article now should work. Let me know!

**Comment by PhantomNX20** [comment]
the plugin is not updated right? cause the plugin on cheshire plugin store is not updated

**Comment by PhantomNX20** [comment]
it seems the plugin don't give me any errors,but how i can test if it works?

**Comment by lucagobbi** [comment]
The plugin itself is separed from the article we just released. If you notice any problem with the plugin, please open a dedicated issue. For testing you just need a running Keycloak instance, configure it following the instructions in the plugin readme and then you're done.

Thank you for spotting that prob!
